title: <p align="center"> Thao </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/thao-nguyen-b65597288/">LinkedIn</a> |
  <a href="https://github.com/thaonguyen2005-work">GitHub</a>
  </p>
  
  <p align="justify">
  I am a sophomore majoring in Data Analytics and Quantitative Economics at Dickinson College. 
  <br><br>
  My journey into the world of data began when I realized its power to transform numbers into actionable insights. For me, working with data is like solving a complex puzzle—cleaning messy datasets, uncovering insights, and visualizing them in a way that sparks clarity and drives decisions.
  <br><br>
  I frequently use Excel, SQL, Python, and R to clean, analyze, and manipulate datasets, while leveraging Power BI and Tableau to design intuitive dashboards that empower stakeholders to make data-informed decisions.
  <br><br>
  Feel free to contact me at: thaonguyenth2005@gmail.com.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

