title: "Thao Nguyen"

logo: "/images/picture.png?raw=true"

description: >
  <p align="center">
    <a href="https://www.linkedin.com/in/thao-nguyen-b65597288/">LinkedIn</a> |
    <a href="https://github.com/thaonguyen2005-work">GitHub</a>
  </p>

  <p align="justify">
    I am a sophomore majoring in Quantitative Economics and Data Analytics. 
    <br><br>
    I am passionate about leveraging data to shape business decisions and enhance operations. Through both coursework and hands-on experience, I have developed strong skills in R, SQL, Python, and Power BI to transform complex datasets into actionable insights.
    <br><br>
    Feel free to contact me at: thaonguyenth2005@gmail.com
    <br><br>
  </p>

theme: jekyll-theme-minimal
